name: Red Hat Developer Toolset
abbreviated_name: Developer Toolset
product_logo: portal.png
current_version: 2.1.0.GA
documentation_path: Red_Hat_Developer_Toolset
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/2.1_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html-single/2.1_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/epub/2.1_Release_Notes/Red_Hat_Developer_Toolset-2-2.1_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/pdf/2.1_Release_Notes/Red_Hat_Developer_Toolset-2-2.1_Release_Notes-en-US.pdf
  User_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/User_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html-single/User_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/epub/User_Guide/Red_Hat_Developer_Toolset-2-User_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/pdf/User_Guide/Red_Hat_Developer_Toolset-2-User_Guide-en-US.pdf
  Developer_Guide: 
    formats:
      html: 
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/chap-DTS.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Developer_Guide/index.html#chap-DTS
description: Red Hat Developer Toolset delivers development agility and production stability
downloads:
skip_maven_instructions: true
other_product: true
